---
apiVersion: v1
kind: Namespace
metadata:
  name: payment-dev
  labels:
    name: payment-dev
    env: dev
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: payment-prod
  labels:
    name: payment-prod
    env: prod
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
